### ISSUE TITLE
Contributing to PkgDev?

### ISSUE THREAD

**Issue by juliohm** [invenia/PkgTemplates.jl#1]
I like the interactive version very much and the customization step by step it provides. I wonder what made you start a new package from scratch instead of adding these features to PkgDev? It is hard to keep up with the pace of Julia, there are many eyes in PkgDev already to update any missing files or formats when new releases come out. It is a lot on the shoulders of a single contributor I would say? :)

Anyways, we definitely this type of flexibility when generating packages, thanks for sharing!

**Comment by christopher-dG** [comment]
Sorry I didn't get to this earlier! Both packages do pretty similar things, but internally they don't work the same. The key difference here is modularity via the plugin system which is the focus of `PkgTemplates`, but not really present at all in `PkgDev`. Because of this, it's not really practical for either package to contain the other.
