### ISSUE TITLE
How to setup template once to have a single command ?

### ISSUE THREAD

**Issue by flip111** [invenia/PkgTemplates.jl#126]
I would like to create a template to my specifications and then be able to run on the command line (not inside of julia) some command to start a new package with my template. Is there any way to do this?

Additionally is there a way to skip the initialization of a git repository?

**Comment by christopher-dG** [comment]
Sorry for the delay! I'm going to answer this question as if you're using the master branch because hopefully it will get released soon.

> I would like to create a template to my specifications and then be able to run on the command line (not inside of julia) some command to start a new package with my template. Is there any way to do this?

Well, you'll just have to write a Julia script and run that from the command line. You can see some tips for saving templates [here](https://invenia.github.io/PkgTemplates.jl/dev/user/#Saving-Templates-1).

> Additionally is there a way to skip the initialization of a git repository?

Yeah, you can disable the `Git` plugin via `Template(; disable_defaults=[Git])`.
