### ISSUE TITLE
TagBot github action?

### ISSUE THREAD

**Issue by oxinabox** [invenia/PkgTemplates.jl#142]
AFAIK the released version does not support tagbot as github action?

**Comment by christopher-dG** [comment]
Released version no, master branch yes

**Comment by oxinabox** [comment]
Yeah that is a problem.
We need to get this release out the door

**Comment by christopher-dG** [comment]
Indeed, if I'm lucky I'll have time to fill in the missing pieces this week.

**Comment by mileslucas** [comment]
Something I want to hitch on here is the awkward interaction between TagBot and Documenter as github actions.

From [here](https://github.community/t5/GitHub-Actions/Github-actions-workflow-not-triggering-with-tag-push/td-p/39685) an action can't trigger another action if they are all on `secrets.GITHUB_TOKEN`. This means that to trigger release builds for documentation you'd have to attach a personal access token. Otherwise users have to manually checkout the TagBot tags, build documentation, and put it into `gh-pages` branch with manual organization.

I don't know (and I doubt) if there is a good way to solve this in the template, but it would at least be a nice piece of documentation to have.

**Comment by DilumAluthge** [comment]
It is already documented. See:
- https://github.com/JuliaRegistries/TagBot/blob/master/README.md#personal-access-tokens
- https://github.com/JuliaRegistries/TagBot/blob/master/README.md#ssh-deploy-keys

**Comment by oxinabox** [comment]
bump

**Comment by christopher-dG** [comment]
Gonna close this, track #148 or #145 instead
