### ISSUE TITLE
Can you create the package without it doing the "git" changes with branches, etc?

### ISSUE THREAD

**Issue by jlperla** [invenia/PkgTemplates.jl#32]
I would love to just be able to generate the templates and do the git stuff entirely myself.  Could that be an option?

**Comment by christopher-dG** [comment]
That's a good idea! Wouldn't be hard to implement either. Obvious downside: No more advertisement in people's commit messages 😅

**Comment by christopher-dG** [comment]
That Git command is just to demonstrate that the files are there, you shouldn't have people run that themselves.

Suppose you create a template and generate the package with Git enabled (in the current release, Git is enabled no matter what), it will create the repo and make some commits for you so that all you have to do is `git push --all` to get it on GitHub. 

If none of the Git stuff is done by PkgTemplates (the PR I just made introduces an option for that), then you have to create the repo, stage and commit the files yourself, and then you can push to GitHub. 

As for GitHub Desktop, I don't really know how to use it as I've never tried. But my guess would be that they have a big button somewhere that says "push" which will take care of the first case I mentioned. In the latter case, they'll have to initialize a repository themselves, etc. as I mentioned.

So if your goal is to make it really easy for people to create a package and put it on GitHub, I would recommend one of two things, basically depending on the experience of your users.

1: If they have used Git before and know what stuff like Travis CI and Codecov are:
```julia
julia> t = generate_interactive("PkgName")
```
This will expose all of the options available to them, but it might be overwhelming to someone unfamiliar with a lot of them.

2: If they're brand new to programming:
```julia
julia> t = Template(; user="username")
julia> generate(t, "PkgName")
```
Or if you want them to have stuff like Travis CI set up for them, you can supply them with a more complicated template:
```julia
julia> t = Template(; user="username", plugins=[TravisCI(), CodeCov(), GitHubPages()])
```
The first case is better if you're just teaching intro programming, and the second is better if you also want to mention best practices like testing and documentation.

Once they have the template created and the package generated, they can run the following:

```julia 
shell> cd $(t.dir)/PkgName  # Enter shell mode by pressing ';' in the REPL
shell> git push --all
```

But they will need to have created the GitHub repo online beforehand.

Hopefully this answers your question, please let me know if I've totally misunderstood it!

**Comment by jlperla** [comment]
Thanks so much, that is exactly what I was looking for.  I think the above instructions would work well for those too stubborn to learn git well, like myself... some people just try to follow instructions sequentially without trying to understand what is going on.

The GitHub desktop thing I was missing was simply that the repo needed to exist on github first before doing the "Public Branch" button.

**Comment by jlperla** [comment]
After figuring out this workflow, though, I don't see a pressing need to provide an option for removing the git stuff you create.  It works well and is very flexible for people to use their own git tools.
