### ISSUE TITLE
Add option for author's email

### ISSUE THREAD

**Issue by juliohm** [invenia/PkgTemplates.jl#4]
Could you please consider adding an option for the author email?

It usually appears in the LICENSE file after the author's name:

https://github.com/juliohm/GeoStats.jl/blob/master/LICENSE

I always generate the package and add it by hand.

**Comment by christopher-dG** [comment]
This is a bit tricky to do elegantly, since there's always the possibility of multiple authors as well as organizations as authors (this repo for example). I think maybe a good solution would be to add the option of providing `authors` as a `Dict` mapping authors to emails, and also perhaps inserting the email when the default `authors` value is given (the large majority of cases). 

For now though, you can hack around it by simply setting `authors="name <email>"`.

**Comment by juliohm** [comment]
I am closing the issue because I really like the suggestion of simply typing all the authors and emails explicitly in a single line. Avoids unnecessary complexity. :+1:

**Comment by christopher-dG** [comment]
Sounds good. I still like the idea of passing a `Dict` or something but I think you might be right, it adds unnecessary complexity.
