### ISSUE TITLE
GPG-sign the commits made by PkgTemplates.jl?

### ISSUE THREAD

**Issue by DilumAluthge** [invenia/PkgTemplates.jl#92]
When PkgTemplates.jl creates a git repo, it makes two commits:
1. `Initial commit` - this commit is empty
2.  ` Files generated by PkgTemplates ` - pretty self-explanatory

Would it be possible to have those two commits automatically signed by my GPG key?

**Comment by christopher-dG** [comment]
Hm, I actually would have expected LibGit2 to use the global Git config (`commit.gpgsign = true`), but it doesn't.
Julia's LibGit2 does not support `git_commit_create_with_signature`. Of course it's only a `ccall` away, but [it looks a bit hairy](https://libgit2.org/libgit2/#v0.28.1/group/commit/git_commit_create_with_signature).
I'd say if you really want this, try to add it to Julia's LibGit2 because the work belongs more there than here.

The alternative is just to use command-line Git... but I'd rather not count on that being installed (even though it is 99% of the time). Another option is to support some flag that says "use Git CLI instead of LibGit2" but I don't really like that complexity.

In the meantime, try this in your repo:
```sh
git filter-branch --commit-filter 'git commit-tree -S "$@";' -- --all
```
